### ISSUE TITLE
Plugin won't load while using citizens.

### ISSUE THREAD

**Issue by Yashero4ka** [derfurkan/OfflinePlayers#3]
**Steps to replicate:**
1. Use purpur 1.19.4
2. Use last version of citizens
3. Use last version of OfflinePlayers
4. Run server
5. Get issue like that:
[latest.log](https://github.com/derfurkan/OfflinePlayers/files/11524192/latest.log)

**Config:**
[config.yml.txt](https://github.com/derfurkan/OfflinePlayers/files/11524201/config.yml.txt)

Without citizens plugin working perfectly.
Thank you in advance!

**Comment by derfurkan** [comment]
Hey!
During my investigation of the issue, I noticed that you are using an outdated version of OfflinePlayers (version 1.5 instead of 1.6).

It's also possible that you are using a version of Citizens that doesn't include any API calls, which prevents OfflinePlayers from accessing Citizens.

**I recommend updating OfflinePlayers to version 1.6 and downloading a Citizens version that supports API calls. You can find the download links [here](https://ci.citizensnpcs.co/job/Citizens2/).**

**Comment by Yashero4ka** [comment]
Many thanks, the problem was solved after your advice. Version 1.5 was on when I was testing to see if it would work with Citizens on the old version when this feature was first added. Thank you very much for such a great plugin!

**Comment by derfurkan** [comment]
No problem! 
Thank you for liking my work i really appreciate that and i mean it!
