### ISSUE TITLE
Bedrock players dont stay

### ISSUE THREAD

**Issue by mozzz14** [derfurkan/OfflinePlayers#6]
When bedrock players join a java server with geyser they dont stay when leaving, just disappear as normal

**Comment by derfurkan** [comment]
It seems like GeyserMC is not firing the PlayerQuitEvent that is used to determine if a player left the server.
Unfortunately i cannot do anything about it since i don't have knowledge about how to use the API for GeyserMC if a API Exists.

If a pull request appears implementing GeyserMC support i will approve it.
